### ISSUE TITLE
sign in failed with PlatformException

### ISSUE THREAD

**Issue by Arunrajpr-2000** [supertokens/supertokens-flutter#60]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 1463): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
E/flutter ( 1463): <asynchronous suspension>
E/flutter ( 1463): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
E/flutter ( 1463): <asynchronous suspension>
E/flutter ( 1463): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
E/flutter ( 1463): <asynchronous suspension>
E/flutter ( 1463): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
E/flutter ( 1463): <asynchronous suspension>

**Comment by rishabhpoddar** [comment]
This does not seem to be an error from supertokens' SDK. Ami missing something?
